[package]
name = "zotfile"
version = "0.1.0"
authors = ["zvkemp <zvkemp@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
ansi_term = "*"
handlebars = "*"
clap = "2"
dirs = "1.0.5"
git2 = "*"
